cs412/urls.py
from django.contrib import admin
from django.urls import path, include ## New import
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("quotes/", include("quotes.urls")), ## new path
    path("restaurant/", include("restaurant.urls")),
    path('mini_fb/', include('mini_fb.urls')),
    path('voter_analytics/', include('voter_analytics.urls')),
     path('project/', include('project.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
# File: views.py
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: The urls structure of my project

from django.urls import path
from .views import RestaurantListView, AvailableTimesView, register, UserReservationListView, MakeReservationView, CancelReservationView, UserReservationListView, CreateReviewView, MyProfileView, UpdateProfileView
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
urlpatterns = [
    path('', RestaurantListView.as_view(), name='restaurant_list'),
    path('restaurants/<int:pk>/times/', AvailableTimesView.as_view(), name='available_times'),
    path('login/', LoginView.as_view(template_name='project/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('restaurant_list')), name='logout', kwargs={'next_page': '/'}),
    path('register/', register, name='register'),
    path('make-reservation/', MakeReservationView.as_view(), name='make_reservation'),
    path('cancel-reservation/<int:pk>/', CancelReservationView.as_view(), name='cancel_reservation'),
    path('my-reservations/', UserReservationListView.as_view(), name='user_reservations'),
    path('restaurants/<int:pk>/reviews/add/', CreateReviewView.as_view(), name='add_review'),
    path('my-profile/', MyProfileView.as_view(), name='my-profile'),
    path('update-profile/', UpdateProfileView.as_view(), name='update-profile'),

]

project/models.py
# File: views.py
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: The models of my project

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import datetime
from django.utils import timezone
import random 
import datetime
from django.conf import settings
class Customer(models.Model):
    """
    Represents a customer with a one-to-one link to the User model.
    
    Attributes:
        user (OneToOneField): A one-to-one link to Django's User model.
        last_name (CharField): Customer's last name.
        first_name (CharField): Customer's first name.
        address (CharField): Customer's address.
        email (EmailField): Customer's email address.
        date_of_birth (DateField): Customer's date of birth.
        phone_number (CharField): Customer's phone number.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    last_name = models.CharField(max_length=100)
    first_name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    email = models.EmailField()
    date_of_birth = models.DateField()
    phone_number = models.CharField(max_length=15)



    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Restaurant(models.Model):
    """
    Represents a restaurant.
    
    Attributes:
        restaurant_name (CharField): Name of the restaurant.
        address (CharField): Address of the restaurant.
        phone_number (CharField): Contact number of the restaurant.
        image (ImageField): Image of the restaurant.
        description (TextField): Description of the restaurant.
        category (CharField): Category of the restaurant cuisine.
    """

    restaurant_name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=15)
    image = models.ImageField(upload_to='restaurant_images/')
    description = models.TextField(blank=True, null=True)
    CATEGORY_CHOICES = [
        ('Asian', 'Asian Food'),
        ('Italian', 'Italian Food'),
        ('Mexican', 'Mexican Food'),
        ('American', 'American Food'),
        ('French', 'French Food'),
    ]
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)

    def __str__(self):
        return self.restaurant_name

class AvailableTime(models.Model):
    """
    Represents time slots available for reservations at a restaurant.
    
    Attributes:
        restaurant (ForeignKey): Link to the Restaurant model.
        available_time (DateTimeField): Specific date and time the slot is available.
        seats_available (IntegerField): Number of seats available for this time slot.
        is_reserved (BooleanField): Indicates if the time slot is already reserved.
    """

    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    available_time = models.DateTimeField()
    seats_available = models.IntegerField()
    is_reserved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.restaurant.restaurant_name} at {self.available_time.strftime('%Y-%m-%d %H:%M')}"

class Reservation(models.Model):
    """
    Represents a reservation made by a customer.
    
    Attributes:
        available_time (ForeignKey): Link to the AvailableTime model indicating the reserved slot.
        customer (ForeignKey): Link to the Customer model for the customer who made the reservation.
        number_of_seats (IntegerField): Number of seats reserved.
    """

    available_time = models.ForeignKey(AvailableTime, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    number_of_seats = models.IntegerField()

    def __str__(self):
        return (f"Reservation for {self.customer} at {self.available_time.restaurant.restaurant_name} "
                f"on {self.available_time.available_time.strftime('%Y-%m-%d %H:%M')}")

    def save(self, *args, **kwargs):
        if self.pk is None:  
            self.available_time.seats_available -= self.number_of_seats
            self.available_time.save()
        super().save(*args, **kwargs)

def load_boston_restaurants():
    boston_restaurants = [
        {"restaurant_name": "Boston Harbor Dining", "address": "101 Harbor Dr, Boston, MA", "phone_number": "617-001-0001", "description": "Seafood and more with a view of Boston Harbor.", "category": "American"},
        {"restaurant_name": "Little Italy Eats", "address": "202 Hanover St, Boston, MA", "phone_number": "617-002-0002", "description": "Authentic Italian dishes in Boston's North End.", "category": "Italian"},
        {"restaurant_name": "Szechuan Chef", "address": "350 Washington St, Boston, MA", "phone_number": "617-003-0003", "description": "Spicy and original Szechuan cuisine.", "category": "Asian"},
        {"restaurant_name": "Le Parisien Bistrot", "address": "59 Temple Pl, Boston, MA", "phone_number": "617-004-0004", "description": "French cuisine with a cozy ambiance.", "category": "French"},
        {"restaurant_name": "El Burrito Loco", "address": "477 Cambridge St, Boston, MA", "phone_number": "617-005-0005", "description": "Vibrant Mexican flavors and giant burritos.", "category": "Mexican"},
        {"restaurant_name": "The Lobster Pot", "address": "303 Congress St, Boston, MA", "phone_number": "617-006-0006", "description": "Fresh lobster and seafood specialties.", "category": "American"},
        {"restaurant_name": "Tokyo Japanese Steakhouse", "address": "22 Kneeland St, Boston, MA", "phone_number": "617-007-0007", "description": "Japanese sushi and hibachi.", "category": "Asian"},
        {"restaurant_name": "The North End Bakery", "address": "215 Hanover St, Boston, MA", "phone_number": "617-008-0008", "description": "Homemade pastries and Italian coffee.", "category": "Italian"},
        {"restaurant_name": "Tandoori Palace", "address": "416 Boylston St, Boston, MA", "phone_number": "617-009-0009", "description": "Traditional Indian dishes and tandoori oven specialties.", "category": "Asian"},
        {"restaurant_name": "Boston Brewery", "address": "306 Northern Ave, Boston, MA", "phone_number": "617-010-0010", "description": "Craft beers and classic American pub food.", "category": "American"},
        {"restaurant_name": "Green Dragon Tavern", "address": "11 Marshall St, Boston, MA", "phone_number": "617-011-0011", "description": "Historic pub with local brews and spirits.", "category": "American"},
        {"restaurant_name": "Pasta Piazza", "address": "45 Winter St, Boston, MA", "phone_number": "617-012-0012", "description": "Fresh pasta and Italian wines.", "category": "Italian"},
        {"restaurant_name": "Canton Dim Sum", "address": "10 Tyler St, Boston, MA", "phone_number": "617-013-0013", "description": "Authentic Cantonese dim sum and teas.", "category": "Asian"},
        {"restaurant_name": "Boston Chop House", "address": "320 Summer St, Boston, MA", "phone_number": "617-014-0014", "description": "Steaks and chops in a sophisticated setting.", "category": "American"},
        {"restaurant_name": "Baja Taco Truck", "address": "12 Carleton St, Boston, MA", "phone_number": "617-015-0015", "description": "Street-style tacos and Mexican sodas.", "category": "Mexican"},
        {"restaurant_name": "Beantown Pho and Grill", "address": "255 State St, Boston, MA", "phone_number": "617-016-0016", "description": "Pho, banh mi, and Vietnamese grills.", "category": "Asian"},
        {"restaurant_name": "The Codfather", "address": "666 Atlantic Ave, Boston, MA", "phone_number": "617-017-0017", "description": "Seafood platters and fish & chips.", "category": "American"},
        {"restaurant_name": "The French Connection", "address": "101 Arch St, Boston, MA", "phone_number": "617-018-0018", "description": "Elegant French dining and wine bar.", "category": "French"},
        {"restaurant_name": "Curry House", "address": "1234 Commonwealth Ave, Boston, MA", "phone_number": "617-019-0019", "description": "Spicy South Indian curry and naan bread.", "category": "Asian"},
        {"restaurant_name": "Bavarian Beerhaus", "address": "789 Boylston St, Boston, MA", "phone_number": "617-020-0020", "description": "German beers and sausages in a rustic setting.", "category": "European"}
    ]

    Restaurant.objects.all().delete()


    for restaurant in boston_restaurants:
        Restaurant.objects.create(**restaurant)

    print("Sample restaurants in Boston loaded successfully!")




def generate_time_slots(start_time, end_time, date):
    """ Helper function to generate time slots for a given date within the operating hours. """
    time_slots = []
    current_time = datetime.datetime.combine(date, start_time)
    while current_time.time() <= end_time:
        time_slots.append(current_time)
        current_time += datetime.timedelta(hours=1)  
    return time_slots

def generate_available_times(seats):
    start_date = timezone.now().date()
    end_date = datetime.date(2025, 1, 1)
    date_delta = datetime.timedelta(days=1)

    default_open_time = datetime.time(11, 0)  # 11 AM
    default_close_time_weekday = datetime.time(21, 0)  # 9 PM
    default_close_time_weekend = datetime.time(22, 0)  # 10 PM

    entries = []
    current_date = start_date
    while current_date <= end_date:
        weekend = current_date.weekday() >= 5  # Weekend check
        close_time = default_close_time_weekend if weekend else default_close_time_weekday
        
        for restaurant in Restaurant.objects.all():
            # Randomly decide if a restaurant opens early
            open_time = datetime.time(8, 0) if random.choice([True, False]) else default_open_time
            
            time_slots = [datetime.datetime.combine(current_date, datetime.time(hour=hour))
                          for hour in range(open_time.hour, close_time.hour + 1)]

            for slot in time_slots:
                entries.append(AvailableTime(

project/forms.py
# File: views.py
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: The forms of my project

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Reservation, AvailableTime, Review, Customer
from django.core.exceptions import ValidationError

class UserRegisterForm(UserCreationForm):
    """
    Custom user registration form extending Django's built-in UserCreationForm.
    
    Attributes:
        first_name (CharField): First name field, required.
        last_name (CharField): Last name field, required.
        email (EmailField): Email field, required.
        address (CharField): Address field.
        date_of_birth (DateField): Date of birth field, with a date picker widget.
        phone_number (CharField): Phone number field.
    """

    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(required=True)
    address = forms.CharField(max_length=255)
    date_of_birth = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    phone_number = forms.CharField(max_length=15)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'address', 'date_of_birth', 'phone_number']

class ReservationForm(forms.ModelForm):
    """
    Form for creating and validating a reservation.
    
    """

    class Meta:
        model = Reservation
        fields = ['available_time', 'number_of_seats']

    def clean(self):
        cleaned_data = super().clean()
        available_time = cleaned_data.get('available_time')
        number_of_seats = cleaned_data.get('number_of_seats')
        if available_time and number_of_seats:
            if available_time.seats_available < number_of_seats:
                raise ValidationError("Not enough seats available.")
        return cleaned_data

class AvailableTimeForm(forms.ModelForm):
    """
    Form for booking a specific number of seats (hidden input by default).

    Initialized with 1 seat for simplicity.
    """
     
    class Meta:
        model = Reservation
        fields = ['number_of_seats']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['number_of_seats'].widget = forms.HiddenInput()
        self.fields['number_of_seats'].initial = 1  # Default to 1 seat

    def clean_number_of_seats(self):
        """
        Validates that the number of seats is a positive integer.

        Returns:
            int: The validated number of seats.
        """

        number_of_seats = self.cleaned_data.get('number_of_seats', 1)  # Default to 1 if not provided
        return number_of_seats



class ReviewForm(forms.ModelForm):
    """
    Form for creating and validating a review.

    Attributes:
        text (TextField): Field for the review text.
        rating (IntegerField): Field for the review rating, must be between 0 and 5.
    """

    class Meta:
        model = Review
        fields = ['text', 'rating']

    def clean_rating(self):
        """
        Validates that the rating is between 0 and 5.

        Returns:
            int: The validated rating value.

        Raises:
            ValidationError: If the rating is outside the allowed range.
        """
         
        rating = self.cleaned_data.get('rating')
        if rating < 0 or rating > 5:
            raise forms.ValidationError("Rating must be between 0 and 5.")
        return rating
    
class CustomerProfileForm(forms.ModelForm):
    """
    Form for editing a customer's profile.
    
    Allows editing of first name, last name, address, email, date of birth, and phone number.
    """
    class Meta:
        model = Customer
        fields = ['first_name', 'last_name', 'address', 'email', 'date_of_birth', 'phone_number']

project/templates/project/available_times.html
<!-- File: available_times.html
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: Show the available times of a restaurant  -->

{% extends 'project/base.html' %}

{% block content %}
<!-- Page Title -->
<!-- Displays the title of the page, dynamically including the restaurant's name. -->

<h1 class="page-title">Available Reservation Times at {{ restaurant.restaurant_name }}</h1>

<!-- Date Filter Form -->
<!-- Allows users to filter available reservation times by selecting a date and a specific time. -->
<form method="get" action="" class="filter-form">
    <input type="date" name="selected_date" value="{{ request.GET.selected_date|default:'' }}" class="filter-input">
    <select name="selected_time" class="filter-input">
        {% for hour in hours_list %}
        <option value="{{ hour }}" {% if request.GET.selected_time == hour %}selected{% endif %}>
            {% with hour|slice:":2" as hour_int %}
                {% if hour_int|add:"0"|slice:":2" < 12 %}
                    {{ hour_int }}:00
                {% else %}
                    {{ hour_int}}:00
                {% endif %}
            {% endwith %}
        </option>
        {% endfor %}
    </select>
    <button type="submit" class="filter-button">Filter by Date and Time</button>
</form>

<!-- Reviews Section -->
<!-- Displays customer reviews and the average rating for the restaurant. -->
<div class="review-section">
    <h2>Customer Reviews</h2>
    {% if reviews %}
        <div class="average-rating">
            <h3>Average Rating: {{ average_rating }}</h3>
            <div class="rating">
                
                {% for _ in unfilled_stars %}
                    <span class="star empty">&#9733;</span> <!-- Unfilled star -->
                {% endfor %}
                {% for _ in filled_stars %}
                    <span class="star">&#9733;</span> <!-- Filled star -->
                {% endfor %}
            </div>
        </div>

        {% for review in reviews %}
            <div class="review">
                <div class="review-header">
                    <strong>{{ review.customer.username }}</strong>
                    <span>{{ review.created_at|date:"Y-m-d" }}</span>
                </div>
                <p class="review-text">{{ review.text }}</p>
            </div>
        {% endfor %}
    {% else %}
        <p class="no-reviews">No reviews yet. Be the first to review!</p>
    {% endif %}

    {% if not user_review %}
        <a href="{% url 'add_review' restaurant.id %}" class="add-review-link">Add Your Review</a>
    {% else %}
        <p class="add-review-link">You have already reviewed this restaurant.</p>
    {% endif %}
</div>


<!-- Available Times Section -->
<!-- Lists available reservation times based on the selected date and time, allowing users to book a reservation. -->
{% if available_times_forms %}
    <h2>Book a Time</h2>
    {% for item in available_times_forms %}
    <form method="post" class="reservation-form">
        {% csrf_token %}
        {{ item.form.number_of_seats.as_hidden }}
        <input type="hidden" name="available_time_id" value="{{ item.time.id }}">
        <div class="reservation-time">
            <p>{{ item.time.available_time|time:"g:i A" }} - {{ item.time.seats_available }} seats available</p>
        </div>
        <button type="submit" class="book-button">Book Now</button>
        {% if item.form.errors %}
            <div class="form-errors">
                {{ item.form.errors }}
            </div>
        {% endif %}
    </form>
    {% endfor %}
{% else %}
    <div class="no-available-times">
        <p>No available times on selected date and time.</p>
    </div>
{% endif %}

{% endblock %}

project/templates/project/base.html
<!-- File: base.html
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: The base of all the html files  -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'project/css/styles.css' %}">
    <!-- Title -->
    <title>Restaurant Reservation System</title>
</head>
<body>
    <header>
        <!-- Navigation Link -->
        <!-- Link to view list of all restaurants -->
        <a href="{% url 'restaurant_list' %}" class="btn btn-create">View Restaurants</a>

        <!-- Authentication Links -->
        <!-- Conditional display based on user authentication status -->

        {% if user.is_authenticated %}
            <div class="auth-links">
                <p>Welcome, {{ user.username }}!</p>
                <a href="{% url 'user_reservations' %}" class="btn btn-create">My Reservations</a>
                <a href="{% url 'my-profile' %}" class="btn btn-create">Profile</a>
                <form action="{% url 'logout' %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-create">Logout</button>
                </form>
            </div>
        {% else %}
            <div class="auth-links">
                <a href="{% url 'login' %}" class="btn btn-create">Login</a>
                <a href="{% url 'register' %}" class="btn btn-create">Register</a>
            </div>
        {% endif %}

        <!-- Search Form -->
        <!-- Form for searching restaurants by name -->

        <div class="search-form">
            <form method="get" action="">
                <input type="text" name="search_name" value="{{ search_name }}" placeholder="Search by restaurant name" />
                <button type="submit" class="btn">Search</button>
            </form>
        </div>
    </header>
    
    <!-- Main Content Area -->
    <!-- This block is overridden by other templates extending this base template -->
    
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
    </footer>
</body>
</html>

project/templates/project/confirm_cancel.html
<!-- File: confirm_cancel.html
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: Ignore this file  -->

{% extends 'project/base.html' %}

{% block content %}
<h2>Confirm Cancellation</h2>
<p>Are you sure you want to cancel this reservation?</p>
<form action="{% url 'cancel_reservation' reservation_id=reservation.id %}" method="post">
{% endblock %}

project/templates/project/create_review.html
<!-- File: create_view.html
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: The page that allow user to create a review for a restaurant -->

{% extends 'project/base.html' %}

{% block content %}
<!-- Review Form Section -->
<!-- This section contains a form for adding a review to a specific restaurant -->

<div class="review-form-section">
    <!-- Title -->
    <!-- Displays the name of the restaurant for which the review is being added -->
    <h5>Add a Review for {{ restaurant.restaurant_name }}</h5>
    <!-- Review Form -->
    <!-- Users submit their review and rating through this form -->

    <form method="post" class="review-form">
        {% csrf_token %}
        <!-- CSRF Token -->
        <!-- Protects against Cross-Site Request Forgery attacks -->

        <!-- Review Textarea -->
        <!-- Allows users to enter their review text -->

        <div class="form-group">
            <label for="id_text" class="form-label">Your Review:</label>
            <textarea name="text" id="id_text" cols="40" rows="5" required placeholder="Share your experience..." class="form-control"></textarea>
        </div>
        
        <div class="form-group">
            <label class="form-label">Your Rating:</label>
            <!-- Rating Input -->
            <!-- Users can select a rating from 1 to 5 stars -->

            <div class="rating">
                {% for star in "54321"|make_list %}
                <input type="radio" id="star{{ star }}" name="rating" value="{{ star }}" required {% if form.rating.value|stringformat:"s" == star %}checked{% endif %}/>
                <label for="star{{ star }}" title="{{ star }} star">&#9733;</label>
                {% endfor %}
            </div>
        </div>
         <!-- Submit Button -->
        <!-- Button for submitting the review form -->
        
        <button type="submit" class="btn-submit">Submit Review</button>
    </form>
</div>
{% endblock %}

project/templates/project/login.html
<!-- File: login.html
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: login page -->
{% extends 'project/base.html' %}

{% block content %}
<!-- Section: Login Header -->
<!-- Displays a simple header for the login page -->

<h6>Login</h6>

<!-- Section: Login Form -->
<!-- Users submit their credentials via this form to log in -->

<section class="login-form-section">
    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <!-- CSRF Token -->
        <!-- Adds a security token to protect against CSRF attacks -->

        {{ form.as_p }}
        <!-- Form Fields -->
        <!-- Renders form fields automatically as paragraphs, provided by Django's form handling -->

        <input type="hidden" name="next" value="{% url 'restaurant_list' %}">
        <!-- Hidden Field for Redirect -->
        <!-- Specifies the page to redirect to after successful login, defaulting to the restaurant list -->

        <button type="submit">Login</button>
        <!-- Submit Button -->
        <!-- Button for submitting the form to log in -->

    </form>
</section>
<!-- Section: Registration Link -->
<!-- Provides a link to the registration page for users who do not have an account -->

<hr>
<p class="registration-create-profile">Don't have an account yet? <a href="{% url 'register' %}">Create your account here</a>.</p>
{% endblock %}

project/templates/project/make_reservation.html
<!-- File: make_reservation.html
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: ignore this file  -->

{% extends 'project/base.html' %}

{% block content %}
<h2>Make a Reservation</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Reserve</button>
</form>
{% endblock %}

project/templates/project/my_profile.html
<!-- File: my_profile.html
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: Show the profile of the user -->
{% extends 'project/base.html' %}

{% block content %}
<!-- Profile Container -->
<!-- This section displays the user's profile information in a formatted manner. -->

<div class="profile-container">
    <h2>My Profile</h2><!-- Title for the profile section -->

    <!-- Conditional Display of Profile Information -->
    {% if customer %}
        <!-- Profile Info Section -->
        <!-- Displays various attributes of the customer's profile if available -->
        <div class="profile-info">
            <p><strong>Name:</strong> {{ customer.first_name }} {{ customer.last_name }}</p>
            <!-- Displays the customer's first and last name -->
            <p><strong>Email:</strong> {{ customer.email }}</p>
            <!-- Displays the customer's email -->
            <p><strong>Address:</strong> {{ customer.address }}</p>
            <!-- Displays the customer's address -->
            <p><strong>Phone Number:</strong> {{ customer.phone_number }}</p>
            <!-- Displays the customer's phone number -->
            <p><strong>Date of Birth:</strong> {{ customer.date_of_birth|date:"Y-m-d" }}</p>
            <!-- Displays the customer's date of birth in YYYY-MM-DD format -->
        </div>
        <!-- Edit Profile Link -->
        <!-- Provides a link to the page where the customer can update their profile -->

        <a href="{% url 'update-profile' %}">Edit Profile</a>
    {% else %}
        <!-- Fallback Message -->
        <!-- This message is displayed if there is no customer information available -->
        <p>No profile information available.</p>
    {% endif %}
</div>
{% endblock %}

project/templates/project/register.html
<!-- File: register.html
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: register page  -->
{% extends 'project/base.html' %}

{% block content %}
<!-- Registration Form Section -->
<!-- This section is dedicated to user registration, including form inputs for user details. -->

<body>

    <div class="registration-form-section">
        <h5>Register</h5>
        <!-- Registration Form -->
        <!-- Method POST ensures that form data is sent securely via HTTP POST. -->
        <form method="post">
            {% csrf_token %}
            <!-- CSRF Token -->
            <!-- Adds a security token to protect against CSRF attacks, essential for all POST forms in Django. -->
        
            {{ form.as_p }}
            <!-- Form Fields -->
            

            <button type="submit">Register</button>
        </form>
        
        <hr>
        <!-- Link to Login Page -->
        <!-- Provides a quick navigation link for users who already have an account and wish to log in. -->
        <p class="registration-create-profile">Already have an account? <a href="{% url 'login' %}">Login here</a>.</p>
    </div>
</body>
{% endblock %}

project/templates/project/update_profile.html
<!-- File: update_profile
# Author: Songwen Zhao (samzhao@bu.edu)
# Description: update the profile of the user page  -->

{% extends 'project/base.html' %}

{% block content %}
<!-- Profile Update Container -->
<!-- This container holds the form used for updating user profile information. -->
<div class="profile-update-container">
    <h2>Update My Profile</h2> <!-- Section heading indicating the purpose of the form -->

    <!-- Update Profile Form -->
    <!-- This form is used for submitting updates to the user's profile information. -->
    <form method="post" class="profile-form">
        {% csrf_token %}
        <!-- CSRF Token -->
        <!-- A security feature to prevent cross-site request forgery attacks. Mandatory for all post forms in Django. -->

        <!-- Form Group: First Name -->
        <!-- This section captures the user's first name. -->
        <div class="form-group">
            <label for="id_first_name">First Name:</label>
            {{ form.first_name }} <!-- Django form field for first name -->
        </div>

        <!-- Form Group: Last Name -->
        <!-- This section captures the user's last name. -->
        <div class="form-group">
            <label for="id_last_name">Last Name:</label>
            {{ form.last_name }} <!-- Django form field for last name -->
        </div>

        <!-- Form Group: Address -->
        <!-- This section captures the user's address. -->
        <div class="form-group">
            <label for="id_address">Address:</label>
            {{ form.address }} <!-- Django form field for address -->
        </div>

        <!-- Form Group: Email -->
        <!-- This section captures the user's email address. -->
        <div class="form-group">
            <label for="id_email">Email:</label>
            {{ form.email }} <!-- Django form field for email -->
        </div>

        <!-- Form Group: Date of Birth -->
        <!-- This section captures the user's date of birth. -->
        <div class="form-group">
            <label for="id_date_of_birth">Date of Birth:</label>
            {{ form.date_of_birth }} <!-- Django form field for date of birth -->
        </div>

        <!-- Form Group: Phone Number -->
        <!-- This section captures the user's phone number. -->
        <div class="form-group">
            <label for="id_phone_number">Phone Number:</label>
            {{ form.phone_number }} <!-- Django form field for phone number -->
        </div>

        <!-- Submit Button -->
        <!-- Button for submitting the form to update the profile. -->
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
{% endblock %}